spring.application.name=revconnect


# ===============================
# SERVER CONFIG
# ===============================

server.port=8080


# ===============================
# ORACLE DATABASE CONFIG
# ===============================

spring.datasource.url=jdbc:oracle:thin:@//localhost:1521/XEPDB1

spring.datasource.username=revconnect

spring.datasource.password=revconnect

spring.datasource.driver-class-name=oracle.jdbc.OracleDriver



# ===============================
# JPA CONFIG
# ===============================

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true

spring.jpa.properties.hibernate.use_sql_comments=true



# ===============================
# HIKARI CONNECTION POOL
# ===============================

spring.datasource.hikari.pool-name=RevConnectPool

spring.datasource.hikari.maximum-pool-size=10



# ===============================
# THYMELEAF CONFIG
# ===============================

spring.thymeleaf.cache=false

# ===============================
# SWAGGER LINK
# ===============================
server.servlet.context-path=/api

# ===============================
# JWT CONFIG
# ===============================

jwt.secret=revconnect-secret-key-very-secure

jwt.expiration=86400000